apiVersion: v1
name: atomix-operator
version: 0.1.0
kubeVersion: ">=1.10.0"
appVersion: 0.1.0
description: AtomixCluster operator
keywords:
  - atomix
  - database
  - cluster
  - operator
home: https://atomix.io
icon: https://atomix.io/assets/img/atomix-fav.png
maintainers:
  - name: kuujo
    email: jordan@opennetworking.org
