apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-init-scripts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  create-config.sh: |
    #!/usr/bin/env bash

    USER=`whoami`
    HOST=`hostname -s`
    DOMAIN=`hostname -d`
    DATA_DIR="/var/lib/atomix/data"
    LOG_DIR="/var/log/atomix"
    LOG_LEVEL=INFO
    NODES=1
    HEAP=2G

    function print_usage() {
    echo "\
    Usage: create-config [OPTIONS]
    Creates an Atomix configuration from the supplied arguments.
        --nodes             The number of nodes in the cluster. The default value is 1.
    "
    }

    function print_variables() {
        echo "atomix.replicas=$NODES"
        for (( i=1; i<=$NODES; i++ ))
        do
            echo "atomix.members.$i=$NAME-$((i))"
        done
    }

    function print_node() {
        echo "cluster.node.id=$NAME-$((ORD+1))"
        echo "cluster.node.address=$NAME-$ORD.$DOMAIN:5679"
    }

    function print_discovery() {
        echo "cluster.discovery.type=bootstrap"
        for (( i=1; i<=$NODES; i++ ))
        do
            echo "cluster.discovery.nodes.$i.id=$NAME-$((i))"
            echo "cluster.discovery.nodes.$i.address=$NAME-$((i-1)).$DOMAIN:5679"
        done
    }

    function create_config() {
        print_variables
        echo "cluster.cluster-id=atomix"
        print_node
        print_discovery
    }

    optspec=":hv-:"
    while getopts "$optspec" optchar; do

        case "${optchar}" in
            -)
                case "${OPTARG}" in
                    nodes=*)
                        NODES=${OPTARG##*=}
                        ;;
                    *)
                        echo "Unknown option --${OPTARG}" >&2
                        exit 1
                        ;;
                esac;;
            h)
                print_usage
                exit
                ;;
            v)
                echo "Parsing option: '-${optchar}'" >&2
                ;;
            *)
                if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                    echo "Non-option argument: '-${OPTARG}'" >&2
                fi
                ;;
        esac
    done

    if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
        NAME=${BASH_REMATCH[1]}
        ORD=${BASH_REMATCH[2]}
    else
        echo "Failed to parse name and ordinal of Pod"
        exit 1
        #NAME=test
        #ORD=0
    fi

    create_config